# ===========================================
#  APPLICATION CONFIG
# ===========================================
spring.application.name=EventApplication
spring.ai.openai.api-key=${MY_API_KEY}


stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://db-mysql-ams3-93716-do-user-21461816-0.i.db.ondigitalocean.com:25060/eventdb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mvc.dispatch-options-request=true
spring.mvc.hiddenmethod.filter.enabled=true


# ===========================================
# SERVER CONFIG
server.port=8080